### ISSUE TITLE
[BUG] Glee subscribes to topics using channel names instead of "channel.address" (v3)

### ISSUE THREAD

**Issue by ivangsa** [asyncapi/glee#732] opened 2024-03-05 08:13 UTC
### Describe the bug.

Glee subscribes to topics using channel names instead of "channel.address" (v3)

https://github.com/asyncapi/glee/blob/master/src/adapters/kafka/index.ts#L66

This may be related to #673

### Expected behavior

It should subscribe to `channel.address`

Also, is very frequent in organizations not to have a dedicated Broker for each environment, and that the channel address depends on the environment.

Maybe this should be configurable somehow..

### Screenshots

This function returns channel names, not channel address.
```ts
    const subscribedChannels = this.getSubscribedChannels()
    await consumer.subscribe({
      topics: subscribedChannels,
      fromBeginning: true,
    })
```

### How to Reproduce

1. I first did this
2. I then did this
3. And so on . . . 

### 🥦 Browser

None

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by KhudaDad414** [comment] 2024-03-05 10:36
> Also, is very frequent in organizations not to have a dedicated Broker for each environment, and that the channel address depends on the environment.

Hey @ivangsa, can you explain this a little more? 🙏

**Comment by ivangsa** [comment] 2024-03-05 10:55
In the last two organizations I worked there is one Kafka Broker for PRO and another shared one for Staging, Integration and Dev

so topics in the shared broker can not use just the same topic name as in PRO, because there would be more than one, so we use a naming convention:

given an asyncapi.yml like: 

```yaml
channels:
  CustomerEventsChannel:
    address: "customer.events"
```
Topics would follow a naming convention similar to this one:

- PRO: `customer.events`
- PRE: `customer.events.pre`
- DEV: `customer.events.dev`

Hope this clarifies the point.

**Comment by fmvilas** [comment] 2024-03-06 12:37
> Topics would follow a naming convention similar to this one:
> 
> PRO: customer.events
> PRE: customer.events.pre
> DEV: customer.events.dev

I think you should be able to solve that if your channel address becomes something like `customer.events.{environment}`. However, this would match `customer.events.pre` and `customer.events.dev` but not `customer.events`. My recommendation is that we don't do any hack on Glee to add stuff to the addresses but instead rely on the AsyncAPI file definitions. If these addresses exist, they should be reflected in the AsyncAPI document and their channels associated with specific servers (like dev or pre).

**Comment by ivangsa** [comment] 2024-03-06 19:44
ok, thanks @fmvilas 

 if I understood, the `{environment}` value can be defined for glee using environment variables, like: 

`GLEE_SERVER_VARIABLES=pre:environment:.pre`

(this would set `environment=.pre` for the `pre` server, mind the dot in `.pre`)

I hope this empty value `GLEE_SERVER_VARIABLES=pro:environment:` would work also for `pro`

This would definitely solve that part.

**Comment by eelcofolkertsma** [comment] 2024-03-11 13:50
Can we have both honored?

Many organizations differentiate between production, and various integration environments (yes!)
Be spec driven: async api spec should support environment differentiation either at server-level or at addressing-level

How about `channel address=customer.events{environment}` and `environment=.pre|.sta|`. Empty for environment than is production

**Comment by eelcofolkertsma** [comment] 2024-03-11 13:54
I am not an experienced developer, but if you feel this is an easy bug I am happy to dive into the mud. Please advise

**Comment by eelcofolkertsma** [comment] 2024-03-11 17:24
Same issue is reported as #721

**Comment by KhudaDad414** [comment] 2024-03-12 14:00
closing since it's a duplicate of #721

**Closed by KhudaDad414** 2024-03-12 14:00 UTC
Labels: bug
